### ISSUE TITLE
XML Error: “Input is not proper UTF-8, indicate encoding!”

### ISSUE THREAD

**Issue by JimmyLv** [imsun/gh-feed#1]
Which happened when I attempt to subscribe http://gh-feed.imsun.net/amfe/article/issues

**Comment by imsun** [comment]
It's because [this issue](https://github.com/amfe/article/issues/25) contains a control character and your client detected it - But I can subscribe it successfully in Feedly.

> ...
> 关于包管理，内部是通过正则表达式匹配项目中的源码 .js 文件， 看看有没有满足的 import 或者 require 语句，然后将其添加到项目目录中的 package.json ，并且调用 npm install 进行安装， Webpack 对项目�打包；相反，检测到包变更，通过 npm uninstall 进行卸载。亲测如果擅自修改 package.json 或者增改 node_modules 的包，很容易就会出错。
> ...

In fact, that "�" is `backspace`. So I filter them out - It's really confusing.
